% test_jar

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));            

% Add files to Java class path
cPathJar = fullfile(...
    cDirThis, ...
    'jar', ...
    'jdk7', ...
    'Sins2Instruments.jar' ...
);

% cPathJar = fullfile(...
%     cDirThis, ...
%     'jar', ...
%     'jdk7', ...
%     'test', ...
%     'Sins2Instruments.jar' ...
% );
        
javaaddpath(cPathJar);

javaclasspath

sins = nus.sins2.Sins2Instruments();
filter = sins.getFilterStage();
maskT = sins.getMaskT();